/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "DoctrFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "DocumentDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "DocumentQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "Documents": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "DocumentsTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "HashLockTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Web": {
      "type": "sst.aws.TanstackStart"
      "url": string
    }
  }
}

import "sst"
export {}