export const _BANKS = [
	{
		bankCode: "0102",
		acronym: "BDV",
		shortName: "Banco de Venezuela",
		fullName: "Banco de Venezuela, S.A. Banco Universal",
		alternativeNames: ["Banco Comercial de Caracas"],
		logoUrl: "https://www.bancodevenezuela.com/assets/img/logo.svg",
	},
	{
		bankCode: "0104",
		acronym: "BVC",
		shortName: "Venezolano de Crédito",
		fullName: "Venezolano de Crédito, S.A. Banco Universal",
		alternativeNames: ["Banco Venezolano de Crédito"],
		logoUrl: "https://www.venezolano.com/images/logo.svg",
	},
	{
		bankCode: "0105",
		acronym: "Mercantil",
		shortName: "Mercantil",
		fullName: "Mercantil Banco, C.A. Banco Universal",
		alternativeNames: ["Banco Mercantil y Agrícola"],
		logoUrl: "https://www.mercantilbanco.com/shared/img/logo.svg",
	},
	{
		bankCode: "0108",
		acronym: "Provincial",
		shortName: "BBVA Provincial",
		fullName: "BBVA Provincial, S.A. Banco Universal",
		alternativeNames: ["Banco Provincial"],
		logoUrl:
			"https://www.provincial.com/content/dam/portal-at-assets/master/images/logo/logo-bbva.svg",
	},
	{
		bankCode: "0114",
		acronym: "Bancaribe",
		shortName: "Bancaribe",
		fullName: "Bancaribe C.A. Banco Universal",
		alternativeNames: ["Banco del Caribe"],
		logoUrl:
			"https://www.bancaribe.com.ve/wp-content/themes/bancaribe/images/logo.svg",
	},
	{
		bankCode: "0115",
		acronym: "Exterior",
		shortName: "Banco Exterior",
		fullName: "Banco Exterior C.A. Banco Universal",
		alternativeNames: ["Exterior"],
		logoUrl: "https://www.bancoexterior.com/assets/img/logo.svg",
	},
	{
		bankCode: "0128",
		acronym: "Caroní",
		shortName: "Banco Caroní",
		fullName: "Banco Caroní, C.A. Banco Universal",
		alternativeNames: [],
		logoUrl: "https://www.bancocaroni.com.ve/images/logo.png",
	},
	{
		bankCode: "0134",
		acronym: "Banesco",
		shortName: "Banesco",
		fullName: "Banesco Banco Universal, S.A.C.A.",
		alternativeNames: ["Banco Agroindustrial Venezolano"],
		logoUrl:
			"https://www.banesco.com/wp-content/themes/banesco/images/logo-banesco.svg",
	},
	{
		bankCode: "0137",
		acronym: "Sofitasa",
		shortName: "Banco Sofitasa",
		fullName: "Banco Sofitasa, Banco Universal, C.A.",
		alternativeNames: ["Sociedad Financiera del Táchira"],
		logoUrl: "https://www.sofitasa.com/images/logo.png",
	},
	{
		bankCode: "0138",
		acronym: "Plaza",
		shortName: "Banco Plaza",
		fullName: "Banco Plaza, Banco Universal, C.A.",
		alternativeNames: [],
		logoUrl: "https://www.bancoplaza.com/images/logo.png",
	},
	{
		bankCode: "0146",
		acronym: "Bangente",
		shortName: "Bangente",
		fullName: "Banco de la Gente Emprendedora, C.A.",
		alternativeNames: [],
		logoUrl: "https://www.bangente.com.ve/images/logo.png",
	},
	{
		bankCode: "0151",
		acronym: "BFC",
		shortName: "Banco Fondo Común",
		fullName: "BFC Banco Fondo Común, C.A. Banco Universal",
		alternativeNames: ["Fondo Común Entidad de Ahorro y Préstamo"],
		logoUrl: "https://www.bfc.com.ve/images/logo_bfc.png",
	},
	{
		bankCode: "0156",
		acronym: "100%Banco",
		shortName: "100% Banco",
		fullName: "100% Banco, Banco Universal, C.A.",
		alternativeNames: ["Financiera de Lara"],
		logoUrl: "https://www.100porcientobanco.com/images/logo.svg",
	},
	{
		bankCode: "0157",
		acronym: "Delsur",
		shortName: "Delsur",
		fullName: "Delsur Banco Universal, C.A.",
		alternativeNames: ["Del Sur Entidad de Ahorro y Préstamo"],
		logoUrl: "https://www.delsur.com.ve/images/logo.png",
	},
	{
		bankCode: "0163",
		acronym: "Tesoro",
		shortName: "Banco del Tesoro",
		fullName: "Banco del Tesoro, C.A. Banco Universal",
		alternativeNames: [],
		logoUrl: "https://www.bt.com.ve/images/logo.svg",
	},
	{
		bankCode: "0166",
		acronym: "BAV",
		shortName: "Banco Agrícola",
		fullName: "Banco Agrícola de Venezuela, C.A. Banco Universal",
		alternativeNames: ["Banco Agrícola de Venezuela"],
		logoUrl: "https://www.bav.com.ve/images/logo.png",
	},
	{
		bankCode: "0168",
		acronym: "Bancrecer",
		shortName: "Bancrecer",
		fullName: "Bancrecer, S.A. Banco Microfinanciero",
		alternativeNames: ["Bancrecer, S.A. Banco de Desarrollo"],
		logoUrl: "https://www.bancrecer.com.ve/images/logo.png",
	},
	{
		bankCode: "0169",
		acronym: "R4",
		shortName: "R4 Banco Microfinanciero",
		fullName: "R4, Banco Microfinanciero C.A.",
		alternativeNames: ["Mi Banco", "Mi Banco, Banco de Desarrollo C.A."],
		logoUrl: "https://www.r4banco.com.ve/images/logo.png",
	},
	{
		bankCode: "0171",
		acronym: "Activo",
		shortName: "Banco Activo",
		fullName: "Banco Activo, C.A. Banco Universal",
		alternativeNames: ["Banco Activo Banco Comercial"],
		logoUrl: "https://www.bancoactivo.com/images/logo.png",
	},
	{
		bankCode: "0172",
		acronym: "Bancamiga",
		shortName: "Bancamiga",
		fullName: "Bancamiga, Banco Universal, C.A.",
		alternativeNames: ["Bancamiga Banco Microfinanciero"],
		logoUrl:
			"https://www.bancamiga.com/wp-content/themes/bancamiga/images/logo.svg",
	},
	{
		bankCode: "0173",
		acronym: "BID",
		shortName: "Banco Internacional de Desarrollo",
		fullName: "Banco Internacional de Desarrollo, C.A. Banco Universal",
		alternativeNames: [],
		logoUrl: "https://www.bid.com.ve/images/logo.png",
	},
	{
		bankCode: "0174",
		acronym: "Banplus",
		shortName: "Banplus",
		fullName: "Banplus Banco Universal, C.A.",
		alternativeNames: ["Banplus Banco Comercial"],
		logoUrl: "https://www.banplus.com/images/logo.svg",
	},
	{
		bankCode: "0175",
		acronym: "BDT",
		shortName: "Banco Digital de los Trabajadores",
		fullName: "Banco Digital de los Trabajadores, Banco Universal C.A.",
		alternativeNames: [
			"Banco Bicentenario del Pueblo",
			"Banco Bicentenario",
			"Banfoandes",
			"Confederado",
			"Central",
			"Bolívar Banco",
		],
		logoUrl: "https://www.bdt.com.ve/images/logo.svg",
	},
	{
		bankCode: "0177",
		acronym: "BANFANB",
		shortName: "BANFANB",
		fullName:
			"Banco de la Fuerza Armada Nacional Bolivariana, Banco Universal, C.A.",
		alternativeNames: [],
		logoUrl: "https://www.banfanb.com.ve/images/logo.svg",
	},
	{
		bankCode: "0178",
		acronym: "N58",
		shortName: "N58 Banco Digital",
		fullName: "N58 Banco Digital, S.A. Banco Microfinanciero",
		alternativeNames: [],
		logoUrl: "https://www.n58.com/images/logo.svg",
	},
	{
		bankCode: "0191",
		acronym: "BNC",
		shortName: "BNC",
		fullName: "Banco Nacional de Crédito, C.A. Banco Universal",
		alternativeNames: ["BOD", "Banco Occidental de Descuento", "Stanford Bank"],
		logoUrl: "https://www.bnconline.com.ve/assets/img/logo-bnc.svg",
	},
	{
		bankCode: "0601",
		acronym: "IMCP",
		shortName: "Crédito Popular",
		fullName: "Instituto Municipal de Crédito Popular",
		alternativeNames: [],
		logoUrl: "https://www.imcp.com.ve/images/logo.png",
	},
];
