# Automatically generated by SST
# pylint: disable=all
# ruff: noqa
from typing import Any

class Resource:
    class App:
        name: str
        stage: str
    class DoctrFunction:
        name: str
        type: str
    class Documents:
        name: str
        type: str
    class DocumentsTable:
        name: str
        type: str
    class HashLockTable:
        name: str
        type: str
    class Web:
        type: str
        url: str

